language: python
python: 2.7
install:
  - "pip install -U pip"
  - "pip install git+https://github.com/lektor/lektor#egg=Lektor"
script:
  - "lektor build"
  - "test \"$TRAVIS_PULL_REQUEST\" == \"false\" && test \"$TRAVIS_BRANCH\" == \"master\" && lektor deploy production"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
