Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Bundler/OrderedGems:
  Enabled: false
