source "https://rubygems.org"

gem "logger", "~> 1.7"
gem "listen", "~> 3.9"

gem "thor", "~> 1.4"

gem "rackup", "~> 2.2"
gem "puma", "~> 6.6"

gem "zeitwerk", "~> 2.7"
gem "concurrent-ruby", "~> 1.3"
gem "dry-inflector", "~> 1.2"

gem "roda", "~> 3.95"
gem "roda-websockets", "~> 0.1.0"
gem "roda-turbo", "~> 1.0"

gem "tilt", "~> 2.6"
gem "erubi"
gem "forme", "~> 2.6"
gem "phlex", "~> 2.3"

gem "sequel", "~> 5.95"
gem "sqlite3", "~> 2.7"

gem "shrine", "~> 3.6"
gem "aws-sdk-s3", "~> 1.197"

gem "marcel", "~> 0.3"
gem "image_processing", "~> 1.0"
gem "mini_exiftool", "~> 2.14"
gem "fastimage", "~> 2.4"

gem "debug", "~> 1.11"
gem "rubocop", require: false
