name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Set up Node 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8.x

      - name: Install deps
        run: |
          bundle install
          yarn install

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build
        env:
          RAILS_ENV: production
          NODE_ENV: production

      - name: Package & Upload
        run : |
          bin/deploy
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

